import mongoose from "mongoose";
import dotenv from "dotenv";
import bcrypt from "bcryptjs";
import User from "../models/userModel.js";
import Listing from "../models/listingModel.js";

dotenv.config();

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("🗃️ Connected to DB");

    // Clear old data
    //await Listing.deleteMany();
    // await User.deleteMany({
    //   email: {
    //     $in: [
    //       "sanju@gmail.com",
    //       "pardheev@gmail.com",
    //       "pardheevkrishna@gmail.com",
    //       "shannu@gmail.com",
    //     ],
    //   },
    // });

    // // Create hashed password
    // const password = await bcrypt.hash("111111", 10);

    // // Create specified users
    // const users = await User.insertMany([
    //   {
    //     name: "sanju",
    //     email: "sanju@gmail.com",
    //     password:
    //       "$2b$10$naxkH1N3rhMb7nNnM4l5yezgNjMPaWgx0MQOWUvhM5axsfYP5Sg2G",
    //     role: "host",
    //     gender: "male",
    //     profileImage: "https://avatar.iran.liara.run/public/boy?username=sanju",
    //     phone: "9876543210",
    //     bio: "Coffee addict ☕ | Book lover 📚 | Professional daydreamer 🌌",
    //     wishlist: [],
    //   },
    //   {
    //     name: "pardheev",
    //     email: "pardheev@gmail.com",
    //     password:
    //       "$2b$10$rBniubT84aC8A1SVN7Ozf.25f9M0rfNBtwrcXNxKtYeQI44zhk1w.",
    //     role: "host",
    //     gender: "male",
    //     profileImage:
    //       "https://avatar.iran.liara.run/public/boy?username=pardheev",
    //     phone: "9876543211",
    //     bio: "Travel enthusiast 🌍 | Foodie at heart 🍜 | Making memories, one adventure at a time",
    //     wishlist: [],
    //   },
    //   {
    //     name: "pardheev krishna",
    //     email: "pardheevkrishna@gmail.com",
    //     password:
    //       "$2b$10$2RI6GqHbypAYIVfHi4hDPeFJZwl2o44f2QIx6Kg7pp.0sRpnbIgKa",
    //     role: "host",
    //     gender: "male",
    //     profileImage:
    //       "https://avatar.iran.liara.run/public/boy?username=pardheev krishna",
    //     phone: "9876543212",
    //     bio: "Tech geek 💻 | Part-time gamer 🎮 | Always debugging life’s errors",
    //     wishlist: [],
    //   },
    //   {
    //     name: "shannu",
    //     email: "shannu@gmail.com",
    //     password:
    //       "$2b$10$C6GJfyCuzX.b7lxGb2Qt7eiaOveog1QDS4V5NmwTgwfQO62/.I.TG",
    //     role: "host",
    //     gender: "female",
    //     profileImage:
    //       "https://avatar.iran.liara.run/public/girl?username=shannu",
    //     phone: "9876543213",
    //     bio: "Fitness freak 🏋️‍♂️ | Dog mom 🐾 | Chasing gains and good vibes",
    //     wishlist: [],
    //   },
    // ]);

    //const hosts = users.filter((user) => user.role === "host");
    const listings = [
      {
        title: "Chic Urban Studio",
        description:
          "Enjoy modern comforts with stunning city views in this chic studio.",
        location: "San Francisco, California",
        latitude: 37.7749,
        longitude: -122.4194,
        price: 342,
        category: "City",
        images: [
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
          "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 3,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.9,
        reviewCount: 52,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: false,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Forest Hideaway Cabin",
        description:
          "Disconnect and unwind in this hidden forest gem surrounded by nature.",
        location: "Seattle, Washington",
        latitude: 47.6062,
        longitude: -122.3321,
        price: 251,
        category: "Mountain",
        images: [
          "https://images.unsplash.com/photo-1600585152220-90363fe7e115",
          "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
          "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 4,
        bedrooms: 2,
        bathrooms: 2,
        rating: 4.7,
        reviewCount: 43,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: true,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Cliffside Coastal Home",
        description:
          "Wake up to crashing waves in this serene coastal home atop a cliff.",
        location: "Sedona, Arizona",
        latitude: 34.8697,
        longitude: -111.7609,
        price: 289,
        category: "Beach",
        images: [
          "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 5,
        bedrooms: 2,
        bathrooms: 2,
        rating: 4.8,
        reviewCount: 35,
        amenities: {
          wifi: true,
          kitchen: false,
          parking: true,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "16:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
      {
        title: "Hilltop Heritage Villa",
        description:
          "Experience timeless charm in a villa with breathtaking hill views.",
        location: "Savannah, Georgia",
        latitude: 32.0809,
        longitude: -81.0912,
        price: 407,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
          "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 6,
        bedrooms: 3,
        bathrooms: 2,
        rating: 4.6,
        reviewCount: 28,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: false,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: false,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: true,
          parties: false,
          checkInTime: "14:00",
          checkOutTime: "12:00",
        },
        status: "pending",
      },
      {
        title: "Lakeside Luxury Retreat",
        description:
          "Luxury living right on the lake with panoramic waterscape views.",
        location: "Portland, Maine",
        latitude: 43.6591,
        longitude: -70.2568,
        price: 367,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
          "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 4,
        bedrooms: 2,
        bathrooms: 2,
        rating: 4.9,
        reviewCount: 50,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: true,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Snowy Mountain Den",
        description:
          "Warm up by the fire after skiing in this cozy mountain chalet.",
        location: "Anchorage, Alaska",
        latitude: 61.2181,
        longitude: -149.9003,
        price: 323,
        category: "Mountain",
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
          "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 6,
        bedrooms: 3,
        bathrooms: 2,
        rating: 4.8,
        reviewCount: 38,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Island Treehouse Escape",
        description:
          "Sleep under the stars in a treehouse with a private beach.",
        location: "Key West, Florida",
        latitude: 24.5551,
        longitude: -81.78,
        price: 298,
        category: "Beach",
        images: [
          "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
          "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
          "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.7,
        reviewCount: 31,
        amenities: {
          wifi: true,
          kitchen: false,
          parking: false,
          tv: false,
          fireplace: false,
          balcony: true,
          heating: false,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: true,
          parties: false,
          checkInTime: "16:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
      {
        title: "Countryside Garden Cottage",
        description:
          "Bright and welcoming, this garden cottage is perfect for peaceful stays.",
        location: "Boulder, Colorado",
        latitude: 40.01499,
        longitude: -105.2705,
        price: 316,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
          "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
          "https://images.unsplash.com/photo-1600585152220-90363fe7e115",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 5,
        bedrooms: 2,
        bathrooms: 2,
        rating: 4.6,
        reviewCount: 19,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: true,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Skyline High‑Rise Condo",
        description:
          "Live the high life in this luxury condo overlooking the city skyline.",
        location: "Charleston, South Carolina",
        latitude: 32.7765,
        longitude: -79.9311,
        price: 459,
        category: "City",
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 4,
        bedrooms: 2,
        bathrooms: 2,
        rating: 4.9,
        reviewCount: 44,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Eco‑Friendly Earth Home",
        description:
          "Sustainable and stylish, this earth home blends nature and comfort.",
        location: "Flagstaff, Arizona",
        latitude: 35.1983,
        longitude: -111.6513,
        price: 289,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
          "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 3,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.7,
        reviewCount: 22,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: false,
          tv: false,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "14:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Zen Riverside Cottage",
        description:
          "Tranquil escape by the river, perfect for meditation and relaxation.",
        location: "Asheville, North Carolina",
        latitude: 35.5951,
        longitude: -82.5515,
        price: 241,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1522156373667-4c7234bbd804",
          "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
          "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 3,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.8,
        reviewCount: 48,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: true,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
      {
        title: "Boho Urban Loft",
        description:
          "Stylish loft in the heart of the city with exposed brick and plants.",
        location: "Denver, Colorado",
        latitude: 39.7392,
        longitude: -104.9903,
        price: 318,
        category: "City",
        images: [
          "https://images.unsplash.com/photo-1549187774-b4e9b0445b06",
          "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.7,
        reviewCount: 33,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: false,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "16:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Bayfront Sunset Villa",
        description:
          "Watch sunsets over the bay from the infinity pool of this luxury villa.",
        location: "Tampa, Florida",
        latitude: 27.9506,
        longitude: -82.4572,
        price: 426,
        category: "Beach",
        images: [
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
          "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 6,
        bedrooms: 3,
        bathrooms: 2,
        rating: 4.9,
        reviewCount: 60,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: true,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Desert Adobe Home",
        description: "Rustic adobe house with natural light and desert views.",
        location: "Santa Fe, New Mexico",
        latitude: 35.687,
        longitude: -105.9378,
        price: 267,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
          "https://images.unsplash.com/photo-1522156373667-4c7234bbd804",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 4,
        bedrooms: 2,
        bathrooms: 2,
        rating: 4.6,
        reviewCount: 29,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: true,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
      {
        title: "Minimalist Skyscraper Flat",
        description:
          "Floor-to-ceiling glass windows with panoramic city views.",
        location: "Chicago, Illinois",
        latitude: 41.8781,
        longitude: -87.6298,
        price: 389,
        category: "City",
        images: [
          "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
          "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
          "https://images.unsplash.com/photo-1522156373667-4c7234bbd804",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.9,
        reviewCount: 55,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: false,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Rustic Log Cabin",
        description:
          "Traditional wooden cabin tucked into a snowy mountain range.",
        location: "Jackson Hole, Wyoming",
        latitude: 43.4799,
        longitude: -110.7624,
        price: 306,
        category: "Mountain",
        images: [
          "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 5,
        bedrooms: 3,
        bathrooms: 2,
        rating: 4.8,
        reviewCount: 40,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "14:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
      {
        title: "Tropical Jungle Bungalow",
        description:
          "Live close to nature in this open-air bungalow surrounded by jungle.",
        location: "Maui, Hawaii",
        latitude: 20.7984,
        longitude: -156.3319,
        price: 362,
        category: "Beach",
        images: [
          "https://images.unsplash.com/photo-1522156373667-4c7234bbd804",
          "https://images.unsplash.com/photo-1549187774-b4e9b0445b06",
          "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.9,
        reviewCount: 61,
        amenities: {
          wifi: false,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: false,
          balcony: true,
          heating: false,
          bbq: true,
        },
        houseRules: {
          smoking: true,
          pets: true,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Hidden Garden Studio",
        description:
          "Private studio with access to lush garden, perfect for artists or writers.",
        location: "San Luis Obispo, California",
        latitude: 35.2828,
        longitude: -120.6596,
        price: 213,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1549187774-b4e9b0445b06",
          "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
          "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.5,
        reviewCount: 25,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "13:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },

      {
        title: "Seaside Surf Shack",
        description:
          "Colorful surf shack with beach access and storage for gear.",
        location: "Malibu, California",
        latitude: 34.0259,
        longitude: -118.7798,
        price: 278,
        category: "Beach",
        images: [
          "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
          "https://images.unsplash.com/photo-1522156373667-4c7234bbd804",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 3,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.8,
        reviewCount: 34,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: false,
          bbq: true,
        },
        houseRules: {
          smoking: true,
          pets: true,
          parties: true,
          checkInTime: "15:00",
          checkOutTime: "12:00",
        },
        status: "pending",
      },
      {
        title: "Cliffside Ocean View Retreat",
        description:
          "Perched on a cliff with panoramic ocean views and sea breeze all day.",
        location: "Big Sur, California",
        latitude: 36.2704,
        longitude: -121.8081,
        price: 520,
        category: "Beach",
        images: [
          "https://images.unsplash.com/photo-1613487956846-b18a5a51d6cc",
          "https://images.unsplash.com/photo-1565182999561-18d7dc61ebf1",
          "https://images.unsplash.com/photo-1618221199790-f54d56efb77d",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 6,
        bedrooms: 3,
        bathrooms: 2,
        rating: 4.9,
        reviewCount: 72,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: true,
          balcony: true,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: true,
          checkInTime: "14:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Cozy Hobbit House",
        description:
          "Live like a hobbit in this fantasy-inspired underground cottage.",
        location: "Bend, Oregon",
        latitude: 44.0582,
        longitude: -121.3153,
        price: 184,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
          "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.7,
        reviewCount: 43,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: true,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
      {
        title: "Ski-In Ski-Out Lodge",
        description:
          "Access the slopes directly from this fully-equipped ski lodge.",
        location: "Aspen, Colorado",
        latitude: 39.1911,
        longitude: -106.8175,
        price: 510,
        category: "Mountain",
        images: [
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
          "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 8,
        bedrooms: 4,
        bathrooms: 3,
        rating: 4.9,
        reviewCount: 96,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: true,
          balcony: true,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "16:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Modern Tiny House",
        description: "A compact, sustainable space with all the essentials.",
        location: "Boise, Idaho",
        latitude: 43.615,
        longitude: -116.2023,
        price: 122,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.6,
        reviewCount: 30,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: false,
          balcony: false,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Vintage Airstream Escape",
        description: "A classic Airstream trailer nestled in the redwoods.",
        location: "Sebastopol, California",
        latitude: 38.4021,
        longitude: -122.8221,
        price: 175,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1522156373667-4c7234bbd804",
          "https://images.unsplash.com/photo-1549187774-b4e9b0445b06",
          "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.8,
        reviewCount: 41,
        amenities: {
          wifi: false,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: true,
          pets: true,
          parties: false,
          checkInTime: "14:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
      {
        title: "Canal Boat Stay",
        description: "Sleep on water in a cozy canal boat with a modern touch.",
        location: "Seattle, Washington",
        latitude: 47.6062,
        longitude: -122.3321,
        price: 298,
        category: "City",
        images: [
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
          "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 4,
        bedrooms: 2,
        bathrooms: 1,
        rating: 4.9,
        reviewCount: 62,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: false,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: true,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "12:00",
        },
        status: "pending",
      },
      {
        title: "Sky Dome Experience",
        description:
          "Glass dome for stargazing and sky views in the open desert.",
        location: "Moab, Utah",
        latitude: 38.5733,
        longitude: -109.5498,
        price: 350,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
          "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.8,
        reviewCount: 67,
        amenities: {
          wifi: true,
          kitchen: false,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: true,
          pets: false,
          parties: false,
          checkInTime: "16:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },

      {
        title: "Luxury Jungle Treehouse",
        description:
          "A treehouse deep in the jungle with 360-degree views and all comforts.",
        location: "Ubud, Bali",
        latitude: -8.5094,
        longitude: 115.2625,
        price: 400,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1549187774-b4e9b0445b06",
          "https://images.unsplash.com/photo-1559599076-0dbe47e4a837",
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 3,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.9,
        reviewCount: 55,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: false,
          tv: false,
          fireplace: false,
          balcony: true,
          heating: false,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: false,
          checkInTime: "14:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
      {
        title: "Private Desert Yurt",
        description:
          "Experience serene desert vibes in a luxury yurt with a private deck.",
        location: "Joshua Tree, California",
        latitude: 34.1347,
        longitude: -116.3131,
        price: 210,
        category: "Adventure",
        images: [
          "https://images.unsplash.com/photo-1535968881458-e8bdf0041f72",
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
          "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.7,
        reviewCount: 38,
        amenities: {
          wifi: false,
          kitchen: false,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: true,
          pets: true,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Chic Downtown Loft",
        description:
          "Stylish loft in the heart of the city, perfect for remote work and relaxation.",
        location: "Austin, Texas",
        latitude: 30.2672,
        longitude: -97.7431,
        price: 310,
        category: "City",
        images: [
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
          "https://images.unsplash.com/photo-1600585153837-96337d0c16a1",
          "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 4,
        bedrooms: 2,
        bathrooms: 2,
        rating: 4.8,
        reviewCount: 89,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: false,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: false,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: true,
          checkInTime: "16:00",
          checkOutTime: "12:00",
        },
        status: "pending",
      },
      {
        title: "Historic Farmhouse Retreat",
        description:
          "Stay in a restored 19th-century farmhouse surrounded by nature.",
        location: "Vermont, USA",
        latitude: 44.5588,
        longitude: -72.5778,
        price: 260,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
          "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
          "https://images.unsplash.com/photo-1618221199790-f54d56efb77d",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 6,
        bedrooms: 3,
        bathrooms: 2,
        rating: 4.6,
        reviewCount: 50,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: true,
          balcony: false,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: true,
          parties: false,
          checkInTime: "15:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
      {
        title: "Lakeview Glass Cabin",
        description:
          "Cabin with full glass walls offering a breathtaking view of the lake.",
        location: "Lake Tahoe, California",
        latitude: 39.0968,
        longitude: -120.0324,
        price: 390,
        category: "Countryside",
        images: [
          "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
          "https://images.unsplash.com/photo-1559599189-2fa7a5a1c2ce",
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
        ],
        hostId: "685254a2191dea6103996164",
        guests: 5,
        bedrooms: 2,
        bathrooms: 1,
        rating: 4.9,
        reviewCount: 78,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: true,
          balcony: true,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: true,
          checkInTime: "14:00",
          checkOutTime: "11:00",
        },
        status: "pending",
      },
      {
        title: "Hilltop Mediterranean Villa",
        description:
          "Enjoy ocean views and luxurious amenities in this Greek-style villa.",
        location: "Santorini, Greece",
        latitude: 36.3932,
        longitude: 25.4615,
        price: 630,
        category: "Beach",
        images: [
          "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
          "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
          "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
        ],
        hostId: "685254a2191dea6103996165",
        guests: 6,
        bedrooms: 3,
        bathrooms: 2,
        rating: 5.0,
        reviewCount: 104,
        amenities: {
          wifi: true,
          kitchen: true,
          parking: true,
          tv: true,
          fireplace: false,
          balcony: true,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: false,
          pets: false,
          parties: true,
          checkInTime: "15:00",
          checkOutTime: "12:00",
        },
        status: "pending",
      },
      {
        title: "Hidden Forest Bungalow",
        description:
          "Relax in a tranquil bungalow surrounded by dense forest and birdsong.",
        location: "Coorg, India",
        latitude: 12.3375,
        longitude: 75.8069,
        price: 180,
        category: "Adventure",
        images: [
          "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
          "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
          "https://images.unsplash.com/photo-1559599076-0dbe47e4a837",
        ],
        hostId: "685254a2191dea6103996163",
        guests: 3,
        bedrooms: 1,
        bathrooms: 1,
        rating: 4.8,
        reviewCount: 60,
        amenities: {
          wifi: false,
          kitchen: true,
          parking: true,
          tv: false,
          fireplace: true,
          balcony: true,
          heating: true,
          bbq: true,
        },
        houseRules: {
          smoking: true,
          pets: true,
          parties: false,
          checkInTime: "14:00",
          checkOutTime: "10:00",
        },
        status: "pending",
      },
    ];

    // Seed listings with precise coordinates and unique images
    // const listings = [
    //   {
    //     title: "Cozy Mountain Cabin Retreat",
    //     description:
    //       "Discover tranquility in this charming mountain cabin nestled among towering pines.",
    //     location: "Aspen, Colorado",
    //     latitude: 39.1911,
    //     longitude: -106.8175,
    //     price: 180,
    //     category: "Mountain",
    //     images: [
    //       "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    //       "https://images.unsplash.com/photo-1600585152220-90363fe7e115",
    //       "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf",
    //     ],
    //     hostId: hosts[0]._id,
    //     guests: 4,
    //     bedrooms: 2,
    //     bathrooms: 1,
    //     rating: 4.7,
    //     reviewCount: 32,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: true,
    //       balcony: false,
    //       heating: true,
    //       bbq: false,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: false,
    //       parties: false,
    //       checkInTime: "15:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Luxury Beachfront Villa",
    //     description:
    //       "Private beach access with stunning ocean views from every room.",
    //     location: "Malibu, California",
    //     latitude: 34.0259,
    //     longitude: -118.7798,
    //     price: 450,
    //     category: "Beach",
    //     images: [
    //       "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    //       "https://images.unsplash.com/photo-1513694203232-719a280e022f",
    //       "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    //     ],
    //     hostId: hosts[1]._id,
    //     guests: 8,
    //     bedrooms: 4,
    //     bathrooms: 3,
    //     rating: 4.9,
    //     reviewCount: 47,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: false,
    //       balcony: true,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "14:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Downtown Luxury Loft",
    //     description: "Modern open-concept loft with panoramic city views.",
    //     location: "New York, New York",
    //     latitude: 40.7128,
    //     longitude: -74.006,
    //     price: 220,
    //     category: "City",
    //     images: [
    //       "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    //       "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    //       "https://images.unsplash.com/photo-1484154218962-a197022b5858",
    //     ],
    //     hostId: hosts[2]._id,
    //     guests: 2,
    //     bedrooms: 1,
    //     bathrooms: 1,
    //     rating: 4.5,
    //     reviewCount: 29,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: false,
    //       tv: true,
    //       fireplace: false,
    //       balcony: true,
    //       heating: true,
    //       bbq: false,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: false,
    //       parties: false,
    //       checkInTime: "16:00",
    //       checkOutTime: "10:00",
    //     },
    //   },
    //   {
    //     title: "Vineyard Cottage",
    //     description: "Charming cottage surrounded by rolling vineyards.",
    //     location: "Napa Valley, California",
    //     latitude: 38.2975,
    //     longitude: -122.2869,
    //     price: 160,
    //     category: "Countryside",
    //     images: [
    //       "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
    //       "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    //       "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    //     ],
    //     hostId: hosts[3]._id,
    //     guests: 3,
    //     bedrooms: 2,
    //     bathrooms: 1,
    //     rating: 4.6,
    //     reviewCount: 21,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: false,
    //       fireplace: true,
    //       balcony: false,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "15:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Lakefront Modern Home",
    //     description: "Floor-to-ceiling windows with breathtaking lake views.",
    //     location: "Lake Tahoe, Nevada",
    //     latitude: 39.0968,
    //     longitude: -120.0324,
    //     price: 300,
    //     category: "Luxury",
    //     images: [
    //       "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    //       "https://images.unsplash.com/photo-1513694203232-719a280e022f",
    //       "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    //     ],
    //     hostId: hosts[0]._id,
    //     guests: 6,
    //     bedrooms: 3,
    //     bathrooms: 2,
    //     rating: 4.8,
    //     reviewCount: 36,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: true,
    //       balcony: true,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: false,
    //       parties: false,
    //       checkInTime: "15:30",
    //       checkOutTime: "11:30",
    //     },
    //   },
    //   {
    //     title: "Minimalist Studio Apartment",
    //     description: "Clean, modern design perfect for digital nomads.",
    //     location: "Portland, Oregon",
    //     latitude: 45.5051,
    //     longitude: -122.675,
    //     price: 100,
    //     category: "Budget",
    //     images: [
    //       "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    //       "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    //       "https://images.unsplash.com/photo-1484154218962-a197022b5858",
    //     ],
    //     hostId: hosts[1]._id,
    //     guests: 2,
    //     bedrooms: 1,
    //     bathrooms: 1,
    //     rating: 4.4,
    //     reviewCount: 19,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: false,
    //       fireplace: false,
    //       balcony: false,
    //       heating: true,
    //       bbq: false,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: false,
    //       parties: false,
    //       checkInTime: "13:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Historic French Quarter Apartment",
    //     description: "Charming apartment in the heart of the French Quarter.",
    //     location: "New Orleans, Louisiana",
    //     latitude: 29.9511,
    //     longitude: -90.0715,
    //     price: 175,
    //     category: "Historical",
    //     images: [
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //       "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5",
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //     ],
    //     hostId: hosts[1]._id,
    //     guests: 4,
    //     bedrooms: 2,
    //     bathrooms: 1,
    //     rating: 4.6,
    //     reviewCount: 28,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: false,
    //       tv: true,
    //       fireplace: false,
    //       balcony: true,
    //       heating: true,
    //       bbq: false,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "15:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Ski-in/Ski-out Chalet",
    //     description: "Luxury chalet with direct access to ski slopes.",
    //     location: "Park City, Utah",
    //     latitude: 40.6461,
    //     longitude: -111.498,
    //     price: 350,
    //     category: "Adventure",
    //     images: [
    //       "https://images.unsplash.com/photo-1518633626580-8ee29d595b94",
    //       "https://images.unsplash.com/photo-1519659528534-7fd733155fc1",
    //       "https://images.unsplash.com/photo-1511880200543-0440f5a69f6e",
    //     ],
    //     hostId: hosts[2]._id,
    //     guests: 8,
    //     bedrooms: 4,
    //     bathrooms: 3,
    //     rating: 4.8,
    //     reviewCount: 42,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: true,
    //       balcony: true,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: false,
    //       parties: false,
    //       checkInTime: "16:00",
    //       checkOutTime: "10:00",
    //     },
    //   },
    //   {
    //     title: "Desert Adobe Retreat",
    //     description:
    //       "Traditional adobe home with modern amenities and private pool.",
    //     location: "Santa Fe, New Mexico",
    //     latitude: 35.687,
    //     longitude: -105.9378,
    //     price: 190,
    //     category: "Historical",
    //     images: [
    //       "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    //       "https://images.unsplash.com/photo-1513694203232-719a280e022f",
    //       "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    //     ],
    //     hostId: hosts[2]._id,
    //     guests: 5,
    //     bedrooms: 3,
    //     bathrooms: 2,
    //     rating: 4.6,
    //     reviewCount: 24,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: true,
    //       balcony: false,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: true,
    //       checkInTime: "14:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Romantic Treehouse Getaway",
    //     description: "Secluded treehouse nestled in the forest canopy.",
    //     location: "Blue Ridge Mountains, Georgia",
    //     latitude: 34.8376,
    //     longitude: -84.3346,
    //     price: 150,
    //     category: "Adventure",
    //     images: [
    //       "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    //       "https://images.unsplash.com/photo-1513694203232-719a280e022f",
    //       "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    //     ],
    //     hostId: hosts[3]._id,
    //     guests: 2,
    //     bedrooms: 1,
    //     bathrooms: 1,
    //     rating: 4.9,
    //     reviewCount: 54,
    //     amenities: {
    //       wifi: false,
    //       kitchen: true,
    //       parking: false,
    //       tv: false,
    //       fireplace: true,
    //       balcony: true,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: false,
    //       parties: false,
    //       checkInTime: "16:00",
    //       checkOutTime: "10:00",
    //     },
    //   },
    //   {
    //     title: "Oceanview Penthouse",
    //     description: "Luxury penthouse with panoramic ocean views.",
    //     location: "Miami, Florida",
    //     latitude: 25.7617,
    //     longitude: -80.1918,
    //     price: 400,
    //     category: "Luxury",
    //     images: [
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //       "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5",
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //     ],
    //     hostId: hosts[3]._id,
    //     guests: 6,
    //     bedrooms: 3,
    //     bathrooms: 2,
    //     rating: 4.9,
    //     reviewCount: 51,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: false,
    //       balcony: true,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "16:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Rustic Log Cabin",
    //     description: "Authentic log cabin with modern amenities in the woods.",
    //     location: "Gatlinburg, Tennessee",
    //     latitude: 35.7143,
    //     longitude: -83.5102,
    //     price: 195,
    //     category: "Mountain",
    //     images: [
    //       "https://images.unsplash.com/photo-1518633626580-8ee29d595b94",
    //       "https://images.unsplash.com/photo-1519659528534-7fd733155fc1",
    //       "https://images.unsplash.com/photo-1511880200543-0440f5a69f6e",
    //     ],
    //     hostId: hosts[3]._id,
    //     guests: 5,
    //     bedrooms: 3,
    //     bathrooms: 2,
    //     rating: 4.7,
    //     reviewCount: 34,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: true,
    //       balcony: false,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "15:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Historic Brownstone",
    //     description: "Elegant brownstone with original architectural details.",
    //     location: "Boston, Massachusetts",
    //     latitude: 42.3601,
    //     longitude: -71.0589,
    //     price: 275,
    //     category: "Historical",
    //     images: [
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //       "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5",
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //     ],
    //     hostId: hosts[2]._id,
    //     guests: 6,
    //     bedrooms: 3,
    //     bathrooms: 2,
    //     rating: 4.6,
    //     reviewCount: 29,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: true,
    //       balcony: false,
    //       heating: true,
    //       bbq: false,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: false,
    //       parties: false,
    //       checkInTime: "16:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Desert Oasis",
    //     description: "Luxury home with private pool in the desert.",
    //     location: "Scottsdale, Arizona",
    //     latitude: 33.4942,
    //     longitude: -111.9261,
    //     price: 320,
    //     category: "Luxury",
    //     images: [
    //       "https://images.unsplash.com/photo-1518633626580-8ee29d595b94",
    //       "https://images.unsplash.com/photo-1519659528534-7fd733155fc1",
    //       "https://images.unsplash.com/photo-1511880200543-0440f5a69f6e",
    //     ],
    //     hostId: hosts[1]._id,
    //     guests: 6,
    //     bedrooms: 3,
    //     bathrooms: 3,
    //     rating: 4.8,
    //     reviewCount: 37,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: false,
    //       balcony: true,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "15:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Waterfront Cottage",
    //     description: "Charming cottage right on the lake with private dock.",
    //     location: "Lake Geneva, Wisconsin",
    //     latitude: 42.5917,
    //     longitude: -88.4334,
    //     price: 210,
    //     category: "Countryside",
    //     images: [
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //       "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5",
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //     ],
    //     hostId: hosts[0]._id,
    //     guests: 4,
    //     bedrooms: 2,
    //     bathrooms: 1,
    //     rating: 4.7,
    //     reviewCount: 33,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: true,
    //       balcony: false,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "15:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Modern Treehouse",
    //     description: "Architect-designed treehouse with luxury amenities.",
    //     location: "Portland, Oregon",
    //     latitude: 45.5051,
    //     longitude: -122.675,
    //     price: 185,
    //     category: "Adventure",
    //     images: [
    //       "https://images.unsplash.com/photo-1518633626580-8ee29d595b94",
    //       "https://images.unsplash.com/photo-1519659528534-7fd733155fc1",
    //       "https://images.unsplash.com/photo-1511880200543-0440f5a69f6e",
    //     ],
    //     hostId: hosts[3]._id,
    //     guests: 2,
    //     bedrooms: 1,
    //     bathrooms: 1,
    //     rating: 4.9,
    //     reviewCount: 48,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: false,
    //       tv: true,
    //       fireplace: false,
    //       balcony: true,
    //       heating: true,
    //       bbq: false,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: false,
    //       parties: false,
    //       checkInTime: "16:00",
    //       checkOutTime: "10:00",
    //     },
    //   },
    //   {
    //     title: "Luxury Penthouse Suite",
    //     description: "Ultra-modern penthouse with city skyline views.",
    //     location: "Chicago, Illinois",
    //     latitude: 41.8781,
    //     longitude: -87.6298,
    //     price: 380,
    //     category: "Luxury",
    //     images: [
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //       "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5",
    //       "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    //     ],
    //     hostId: hosts[1]._id,
    //     guests: 4,
    //     bedrooms: 2,
    //     bathrooms: 2,
    //     rating: 4.8,
    //     reviewCount: 39,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: false,
    //       balcony: true,
    //       heating: true,
    //       bbq: false,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: false,
    //       parties: false,
    //       checkInTime: "16:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Seaside Cottage",
    //     description: "Charming cottage steps from the beach with ocean views.",
    //     location: "Cape Cod, Massachusetts",
    //     latitude: 41.6688,
    //     longitude: -70.2962,
    //     price: 230,
    //     category: "Beach",
    //     images: [
    //       "https://images.unsplash.com/photo-1518633626580-8ee29d595b94",
    //       "https://images.unsplash.com/photo-1519659528534-7fd733155fc1",
    //       "https://images.unsplash.com/photo-1511880200543-0440f5a69f6e",
    //     ],
    //     hostId: hosts[1]._id,
    //     guests: 4,
    //     bedrooms: 2,
    //     bathrooms: 1,
    //     rating: 4.7,
    //     reviewCount: 35,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: true,
    //       balcony: false,
    //       heating: true,
    //       bbq: true,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "15:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Urban Artist Loft",
    //     description: "Creative space in the heart of the arts district.",
    //     location: "Austin, Texas",
    //     latitude: 30.2672,
    //     longitude: -97.7431,
    //     price: 140,
    //     category: "City",
    //     images: [
    //       "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    //       "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    //       "https://images.unsplash.com/photo-1484154218962-a197022b5858",
    //     ],
    //     hostId: hosts[1]._id,
    //     guests: 3,
    //     bedrooms: 1,
    //     bathrooms: 1,
    //     rating: 4.3,
    //     reviewCount: 18,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: false,
    //       balcony: true,
    //       heating: true,
    //       bbq: false,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "15:00",
    //       checkOutTime: "11:00",
    //     },
    //   },
    //   {
    //     title: "Historic Farmhouse",
    //     description: "Renovated 19th century farmhouse with modern comforts.",
    //     location: "Lancaster, Pennsylvania",
    //     latitude: 40.0379,
    //     longitude: -76.3055,
    //     price: 130,
    //     category: "Historical",
    //     images: [
    //       "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    //       "https://images.unsplash.com/photo-1513694203232-719a280e022f",
    //       "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    //     ],
    //     hostId: hosts[0]._id,
    //     guests: 6,
    //     bedrooms: 3,
    //     bathrooms: 2,
    //     rating: 4.5,
    //     reviewCount: 31,
    //     amenities: {
    //       wifi: true,
    //       kitchen: true,
    //       parking: true,
    //       tv: true,
    //       fireplace: false,
    //       balcony: false,
    //       heating: true,
    //       bbq: false,
    //     },
    //     houseRules: {
    //       smoking: false,
    //       pets: true,
    //       parties: false,
    //       checkInTime: "15:00",
    //       checkOutTime: "12:00",
    //     },
    //   },
    // ];
    await Listing.insertMany(listings);

    console.log("✅ Seed data inserted successfully.");
    process.exit();
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
    process.exit(1);
  }
};

seed();
